name: Deploy App to EC2 using CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare deploy-info
      run: |
        echo "{\"repo\":\"${GITHUB_REPOSITORY}\",\"commit\":\"${GITHUB_SHA}\"}" > deploy-info.json

    - name: Zip deploy package
      run: zip -r artifact.zip . -x '*.git*' -x '.github/*'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Upload artifact to S3
      run: aws s3 cp artifact.zip s3://lucyzenger-codedeploy-artifacts/${GITHUB_SHA}.zip


    - name: Trigger CodeDeploy deployment
      run: |
        aws deploy create-deployment \
        --application-name code-deploy-practice \
        --deployment-group-name code-deploy-practice-group \
        --s3-location bucket=lucyzenger-codedeploy-artifacts,key=${GITHUB_SHA}.zip,bundleType=zip

